/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "JavaFunction.h"
#include "Function.h"
#include "Differentiator.h"
using namespace std;
/* Header for class de_lab4inf_wrb_Differentiator */

#ifndef _Included_de_lab4inf_wrb_Differentiator
#define _Included_de_lab4inf_wrb_Differentiator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_lab4inf_wrb_Differentiator
 * Method:    differentiate
 * Signature: (Lde/lab4inf/wrb/Function;DD)D
 */
JNIEXPORT jdouble JNICALL Java_diffIntegrate_Differentiator_differentiate
  (JNIEnv * env, jobject obj, jobject fct, jdouble x, jdouble eps) {
	double dF =0;
	    try {
	        JavaFunction f = JavaFunction(env,fct);
	        dF = differentiate(f, x, eps);
	    } catch(const char* error) {
	        jclass jExcepClazz = env->FindClass("java/lang/ArithmeticException");
	        env->ThrowNew(jExcepClazz, error);
	    }
	    return (dF);
}

#ifdef __cplusplus
}
#endif
#endif
